### ISSUE TITLE
maybe a throw exception bug.

### ISSUE THREAD

**Issue by zhangyuchun** [nykytenko/onyx-log#3]
I use onyx-log in 
https://github.com/huntlabs/common/blob/master/source/zhang2018/common/Log.d .

only happend once at now ! 

but i found at first it work finely and can write log into file  , after a while then programe don't hold the handle any more ( lsof test.log),  and  workCycle() nerver execute ( gdb break ) .
so i think controller.saveMsg(msg) or controller.flush , throw a exception , and not catch . so this is thread was termited.

private void workCycle()
	{
		receiveTimeout(
			dur!("msecs")(10),
			(string msg)
			{
				controller.saveMsg(msg);
			},
			(OwnerTerminated e){workStatus = AppenderWorkStatus.STOPPING;},
			(Variant any){}
		);

		if (logFileWriteFlushPeriod <= (Clock.currStdTime() - startFlushTime)/(1000*10))
		{
			controller.flush;
			startFlushTime = Clock.currStdTime();
		}
	}

**Comment by nykytenko** [comment]
Thank, zhangyuchun.
I'm published new release v1.2.5 with added exception processing.
